spring.application.name=apigateway
server.port=8080

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Enable Gateway Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=UserService
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=AppointmentService
spring.cloud.gateway.routes[1].uri=lb://APPOINTMENTSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/appointments/**

spring.cloud.gateway.routes[2].id=ConfirmedAppointmentService
spring.cloud.gateway.routes[2].uri=lb://CONFIRMEDAPPOINTMENTSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/confirmed/**


spring.cloud.gateway.routes[3].id=AdminService
spring.cloud.gateway.routes[3].uri=lb://ADMINSERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**


spring.cloud.gateway.routes[4].id=DoctorService
spring.cloud.gateway.routes[4].uri=lb://DOCTORSERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/doctors/**